language: php

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  global:
    # Couscous deploy configuration
    - GIT_NAME="'phUML documentation'"
    - GIT_EMAIL=montealegreluis@gmail.com
    - GH_REF=github.com/MontealegreLuis/phuml
    - secure=PTctakC76z6fqgkUQrRsVZta2NOnJFdZ79ieKeX/srCeqn6z5bxV4iMzPpvJO4Hx9Ku0ms0A3XBZaGoouHcI9jtZ4n6GJ1e5j0nGF5GzBf9y0f2sBj8GXj58v2xKBqw1cKODr3a0RSGVAy9zuoRNGJBI7cZbP2jAC8wcLAVmAgKW9kPKZKFDy9wH+OQJMgZV4/8MrMWGp1NPZRnBRnAZRExYoH9vCaWtB48eGsOQYtdF1rwxtg2U4uZwkcoNv9e9/8ABhkXn9sPfG1flYFqYYGI3eO7ZYUAdwWYNXnjgJhetXCHzfTJgMKyh9oLOeZ8S8NpaML67Br6DGrjfuCYpDe/Rl0b7hivs7d0yPXBy0qbRmvDX1JodZmFLV2G7mqGqWdWfDxvUjGepNHHOponqXcLTI8OycVsmycWJOH1SFikY5Nqoa06XjcvsNTfZ/2NqmqHfcaofqIlwxa7za9fdLjcBuU3OzKy9qnCNtD5yaBO+wDDTF43xEnEvo8/3N/zXiYixTMTUq1+MvldlIF9OwXXxEz58QUTNhuLOFQDp76vHHsXmYLo+OzCYsJmGaPTLfOCwJzYqskxasOPu96LjMD/jVyqtBHa3ABvFiAjzMuK+frvQJF4EU1J5yn/h+1CgBKsA82L5UhZc8lCylfP59ppvjrZcNc2P4lykuHiHEMM=

matrix:
  include:
    - php: 7.1
      env:
        - EXECUTE_DEPLOYMENT=true
    - php: 7.2
  allow_failures:
    - php: 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # We need GraphViz to create the UML diagrams
  - sudo apt-get install graphviz
  # Install Imagick extension
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - yes | pecl install imagick
  - openssl aes-256-cbc -K $encrypted_2ff9b681a952_key -iv $encrypted_2ff9b681a952_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - curl -OS http://couscous.io/couscous.phar
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then php couscous.phar travis-auto-deploy --php-version $TRAVIS_PHP_VERSION ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./phar.sh ; fi
